modkey: Mod4
alt_modkey: Mod1

terminal: x-terminal-emulator

autorun_apps:
    - 'xrdb -load ~/.Xresources'
    - 'setxkbmap -config ~/.keyboard'
    - 'unclutter -idle 1 -root'
    - 'xrandr-setup'

inet_interface: wlo1

clock_format: %A %B %d, %I:%M%p

# wiboxes?
# keys?
